# Generated by Django 4.2.5 on 2023-09-21 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managementstore',
            old_name='createAt',
            new_name='createdAt',
        ),
    ]
