# Generated by Django 4.2.5 on 2023-10-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_createat_managementstore_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementstore',
            name='description',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='managementstore',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='managementstore',
            name='stock',
            field=models.CharField(max_length=255),
        ),
    ]
